name: advent14_google_map
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.0.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true